### ISSUE TITLE
Issue with training

### ISSUE THREAD

**Issue by DanielDiGiovanni-py** [AliciaDurrer/DM_Inpainting#1]
Hi, I'm trying to use your DDPM_Pseudo3D model on some liver MRI data I have, but the training process keeps getting "Killed". I think this is because the model is setup for distributed processing, is there an easy way to have this work on a single GPU?

**Comment by JiashiYin** [comment]
Hey, how did you solve this? I also keep getting Killed upon dataloader creation.

**Comment by AliciaDurrer** [comment]
Hi, 
it is possible to train only on a single GPU (this is also how we did it). This is defined in the function dist_util.py (line 28: os.environ["CUDA_VISIBLE_DEVICES"] = "1"). You can specify your device there. In case you only have one GPU available and not several to choose from it may not have worked because the default here is the second (sorry, my bad). You have to set it to "0". Hope this helps.
